services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: production-rag-api
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - rag-network
    depends_on:
      - qdrant

networks:
  rag-network:
    external: true

volumes:
  qdrant_storage:
    external: true